### PR TITLE
Get latest mandrel when `version` not specified

### PR DESCRIPTION
**Pull request by zakkak**
- Get latest mandrel release if version not specified
- Remove user-agent from HttpClient constructor

### CODE REVIEW

**Comment by fniephaus** [comment]
Please regenerate the dist files.

**Comment by zakkak** [comment]
> Please regenerate the dist files.

Regenerated and added an extra test in CI

**Review by fniephaus — APPROVED** [review]
LGTM

**Comment by zakkak** [comment]
Shall I rebase?

**Comment by fniephaus** [comment]
>Shall I rebase?

Nope, it's fine.

**Comment by zakkak** [comment]
Thank you @fniephaus

**Pull request merged**
